---
title: "Convolutional_Network"
author: "Elizabet Sanyal"
date: "2023-06-18"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("custom_nn_keras.R", local = knitr::knit_global())

```

```{r, warning=FALSE, message=FALSE}
library(reticulate)
library(tensorflow)
library(abind)
library(keras)
library(xts)
library(PerformanceAnalytics)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(purrr)
load("~/R/Test_GPU/data_ml.RData")
stock_ids <- levels(as.factor(data_ml$stock_id)) 
stock_days <- data_ml %>%                        
    group_by(stock_id) %>% summarize(nb = n()) 
stock_ids_short <- stock_ids[which(stock_days$nb == max(stock_days$nb))] # Stocks with full data
returns <- data_ml %>%                           
    filter(stock_id %in% stock_ids_short) %>%    
    dplyr::select(date, stock_id, R1M_Usd) %>%   
    spread(key = stock_id, value = R1M_Usd)

features <- colnames(data_ml[3:95]) # Keep the feature's column names (hard-coded, beware!)
features_short <- c("Div_Yld", "Eps", "Mkt_Cap_12M_Usd", "Mom_11M_Usd", 
                    "Ocf", "Pb", "Vol1Y_Usd", "Debtequity", "Cash_Per_Share", "Asset_Turnover")

data_short <- data_ml %>%         # Shorter dataset
    filter(stock_id %in% stock_ids_short) %>%
    dplyr::select(c("stock_id", "date",features_short, "R1M_Usd"))
dates <- unique(data_short$date)  # Vector of dates for the training period

glimpse(data_short)

```


```{r}

data_wide <- data_short %>%  select(-R1M_Usd)%>%
  pivot_wider(names_from = stock_id, values_from = Div_Yld:Asset_Turnover) %>%
  arrange(date) %>% 
  select(-date) 

returns <- data_short %>%  
  select(R1M_Usd,stock_id, date) %>%
  pivot_wider(names_from = stock_id, values_from = R1M_Usd) %>% 
  arrange(date) %>% 
  select(-date)

```


```{r}
library(keras)



build_conv_model <- function(n_stocks, learning_rate, data, loss = sharpe_ratio_loss,timesteps=12 ) {
  
  num_features <- dim(data)[3]
  model_sequential <- keras_model_sequential() 
  model_sequential%>%
    layer_conv_1d(filters=64, kernel_size=5, activation="relu",
               input_shape = c(timesteps, num_features)
    ) %>% layer_conv_1d(filters=32, kernel_size=4, activation="relu"
    )%>% layer_conv_1d(filters=16, kernel_size=4, activation="relu"
    ) %>% layer_flatten() %>% layer_dense(units = n_stocks,
                activation = "tanh")%>% 
    layer_dense(units = n_stocks,
                activation = "linear") %>%  layer_lambda(row_scale) %>% 
    layer_lambda(w_full_constraint_leverage)
  
  model_sequential %>% compile(
    loss = loss,
    optimizer = optimizer_rmsprop(learning_rate =as.double(learning_rate))
  ) 
  
  return(model_sequential)
}
```




