---
title: "Main"
author: "Elizabet Sanyal"
date: "2023-06-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("custom_nn_keras.R", local = knitr::knit_global())
source("data_preparation.R", local = knitr::knit_global())
```

```{r, warning=FALSE, message=FALSE}
library(reticulate)
library(tensorflow)
library(abind)
library(keras)
library(xts)
library(PerformanceAnalytics)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(purrr)
load("~/R/Test_GPU/data_ml.RData")
stock_ids <- levels(as.factor(data_ml$stock_id)) 
stock_days <- data_ml %>%                        
    group_by(stock_id) %>% summarize(nb = n()) 
stock_ids_short <- stock_ids[which(stock_days$nb == max(stock_days$nb))] # Stocks with full data
returns <- data_ml %>%                           
    filter(stock_id %in% stock_ids_short) %>%    
    dplyr::select(date, stock_id, R1M_Usd) %>%   
    spread(key = stock_id, value = R1M_Usd)

features <- colnames(data_ml[3:95]) # Keep the feature's column names (hard-coded, beware!)
features_short <- c("Div_Yld", "Eps", "Mkt_Cap_12M_Usd", "Mom_11M_Usd", 
                    "Ocf", "Pb", "Vol1Y_Usd", "Debtequity", "Cash_Per_Share", "Asset_Turnover")

data_short <- data_ml %>%         # Shorter dataset
    filter(stock_id %in% stock_ids_short) %>%
    dplyr::select(c("stock_id", "date",features, "R1M_Usd"))
dates <- unique(data_short$date)  # Vector of dates for the training period

```


```{r}

data_wide <- data_short %>%  select(-R1M_Usd)%>%
  pivot_wider(names_from = stock_id, values_from = features) %>%
  arrange(date) %>% 
  select(-date) 

returns <- data_short %>%  
  select(R1M_Usd,stock_id, date) %>% mutate(across(
    c(R1M_Usd),
    ~ winsorize(., 0.01)
  )) %>% 
  pivot_wider(names_from = stock_id, values_from = R1M_Usd) %>% 
  arrange(date) %>% 
  select(-date)



returns_test <- data_short %>%  
  select(R1M_Usd,stock_id, date)  %>% 
  pivot_wider(names_from = stock_id, values_from = R1M_Usd) %>% 
  arrange(date) %>% 
  select(-date)
```
layer: 2.0
l1_value_lin: 0.0
l2_value_lin: 1e-05
l1_value_nlin: 0.0
l2_value_nlin: 1e-05
rate: 0.1
units_lin: 1
units_nlin_i: 2701
activation_nl_i: sigmoid
units_conc: 2901
activation_conc: tanh
learning_rate: 0.01
units_nlin_ii: 501
activation_nl_ii: tanh
Score: 0.28065088391304016

```{r}
rate <- 0.1
units_lin <-  1
units_nlin_i <- 2701
activation_nl_i <- "sigmoid"
units_conc <- 2901
activation_conc <- "tanh"
learning_rate <-0.01
units_nlin_ii <- 501
activation_nl_ii <-"tanh"
l2_value_lin <- 1e-05
l2_value_nlin <- 1e-05
build_model <- function(rate, units_lin,units_nlin_i, activation_nl_i,units_conc,activation_conc,learning_rate,units_nlin_ii, activation_nl_iiб, data ){
     temp <- units_nlin_ii
     temp <- activation_nl_ii
     num_features <- ncol(data)
    layer_1 <- layer_input(shape = c(num_features), 
                           name = "Linear_Model_Input")
    
    layer_linear <-  layer_1 %>% 
                           layer_dense(units = units_lin, 
                                       activation = "linear",
                                       kernel_initializer = initializer_random_normal(mean = 0, stddev = 0.04),
                                       kernel_regularizer = regularizer_l1_l2(l1 = 0, l2 =l2_value_lin )
                                       ) %>%
                           layer_batch_normalization(scale = TRUE, center = TRUE) %>%
                           layer_dropout(rate = rate) 
    
     layer_2 <- layer_input(shape = c(num_features), name = "Non-Linear_Model_Input")
     
     layer_nonlinear <- layer_2 %>% layer_dense(units = units_nlin_i,
                                                activation = activation_nl_i,
                                                kernel_initializer = initializer_random_normal(mean = 0, stddev = 0.04),
                                                 kernel_regularizer = regularizer_l1_l2(l1 = 0, l2 =l2_value_nlin )
                                                )  %>% layer_dropout(rate = rate)  
       
      layer_nonlinear <- layer_nonlinear %>%  layer_dense(units = units_nlin_ii,                                                                                          activation = activation_nl_ii,kernel_initializer = initializer_random_normal(mean = 0.05, stddev = 0.05))

      concat <- layer_concatenate(list(layer_linear, layer_nonlinear))
      layer_3 <- concat %>%
                    layer_dense(units = units_conc, 
                                activation = activation_conc, 
                                kernel_initializer = initializer_random_normal(mean = 0, stddev = 0.04))  %>% 
                                 layer_batch_normalization(scale = TRUE, center = TRUE)

# Define the rest of the model
        output <- layer_3 %>%
                 layer_dense(units = length(stock_ids_short), 
                             activation = "linear",
                             kernel_initializer = initializer_random_normal(mean = 0, stddev = 0.04))  %>% 
          layer_lambda(w_full_constraint_leverage) # full investment constrain with no legerage allowed

          model <- keras_model(inputs = list(layer_1, layer_2), outputs = output)

# Compile the model
           model %>% compile(
               loss = sharpe_ratio_loss,
               optimizer = optimizer_adam(learning_rate = learning_rate,clipnorm=1)
                             
                             )
           return(model)
} 


```

```{r}
# Define dropout rate

num_features <- ncol(data_wide)
val_window <- 60
training_window <- 60
 
backtest <- function(t, data_wide, returns) {
 
  
    window_data <- as.matrix(data_wide[1:t,])
    window_returns <- as.matrix(returns[1:t,])
    val_window_data <- as.matrix(data_wide[t:(t+val_window),])
    val_returns <- as.matrix(returns[t:(t+val_window),])
    data_predict <- as.matrix(data_wide[(t+1+val_window),])
    
    model <- build_model(rate, units_lin,units_nlin_i, activation_nl_i,units_conc,activation_conc,learning_rate,units_nlin_ii, activation_nl_ii, data_wide )
    
    
     early_stopping <- callback_early_stopping(monitor = "val_loss",
                                               patience = 15,
                                               restore_best_weights = TRUE
                                               )
     
    
    lr_callback <- callback_reduce_lr_on_plateau( monitor = 'val_loss',
                                                  factor = 0.01, 
                                                  patience = 5,
                                                  verbose = 1,
                                                  mode = 'auto'
                                                  )




    model %>% fit( x = list(window_data, window_data), 
                                   y = window_returns, 
                                   epochs = 60, 
                                   batch_size = 60, 
                                   verbose = 2,  
                                   validation_data = list(list(val_window_data, val_window_data), val_returns),
                                   shuffle=FALSE,
                                   callbacks = list(early_stopping, lr_callback)
                   )
    
    prediction_w_t <- predict(model, list(data_predict,data_predict))
    
                              
  return(prediction_w_t)
}


```



```{r}


testing_periods <-  nrow(data_wide)-training_window-val_window
#max possible nrow(data_wide)-training_window-val_window

t_values <- seq(60, 60+testing_periods)

backtest_results <- map(t_values, backtest, data_wide, returns)

test_sample_returns <- as.matrix(returns_test[(training_window+val_window+1):(training_window+val_window+testing_periods+1),])
weights_sample_returns <- do.call(rbind, lapply(backtest_results, unlist))
test_pf_ret <- rowSums(weights_sample_returns *  test_sample_returns)

#Metrics:

mean(test_pf_ret, na.rm = TRUE)/sd(test_pf_ret, na.rm = TRUE)
```



